batch.make_nearRT.2006.csh
batch.make_nearRT.2007.csh
batch.make_nearRT.2008.csh
cp -r /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200601 /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200602 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200603 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200604 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200605 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200606 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200607 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200608 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200609 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200610 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200611 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200612 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200701 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200702 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200703 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200704 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200705 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200706 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200707 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200708 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200709 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200710 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200711 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200712 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200801 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200802 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200803 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200804 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200805 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
wrap_append.pl /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp /raid8/forecast/sw_monitor/data/conus.new/forcing/curr_spinup/asc_vicinp.200806 data /raid8/forecast/sw_monitor/data/conus.new/forcing/spinup_nearRT/asc_vicinp
