#wrap_prep_for_kingtse.pl vic ../data/conus.new/results/retro/vic/daily/asc fluxes ../data/conus.new/results/retro/vic/daily/asc.tmp ../data/conus.new/results/retro/vic/daily/asc.tmp2 ../data/conus.new/results/retro/vic/monthly/asc sm
#wrap_prep_for_kingtse.pl clm ../data/conus.new/results/retro/clm/daily/asc wb ../data/conus.new/results/retro/clm/daily/asc.tmp ../data/conus.new/results/retro/clm/daily/asc.tmp2 ../data/conus.new/results/retro/clm/monthly/asc sm
wrap_prep_for_kingtse.pl noah_2.8.new ../data/conus.new/results/retro/noah_2.8.new/daily/asc wb ../data/conus.new/results/retro/noah_2.8.new/daily/asc.tmp ../data/conus.new/results/retro/noah_2.8.new/daily/asc.tmp2 ../data/conus.new/results/retro/noah_2.8.new/monthly/asc sm
#wrap_prep_for_kingtse.pl sac.new ../data/conus.new/results/retro/sac.new/daily/asc wb ../data/conus.new/results/retro/sac.new/daily/asc.tmp ../data/conus.new/results/retro/sac.new/daily/asc.tmp2 ../data/conus.new/results/retro/sac.new/monthly/asc sm

#wrap_prep_ro_for_kingtse.pl vic ../data/conus.new/results/retro/vic/daily/asc fluxes ../data/conus.new/results/retro/vic/daily/asc.tmp ../data/conus.new/results/retro/vic/daily/asc.tmp2 ../data/conus.new/results/retro/vic/monthly/asc ro
#wrap_prep_ro_for_kingtse.pl clm ../data/conus.new/results/retro/clm/daily/asc wb ../data/conus.new/results/retro/clm/daily/asc.tmp ../data/conus.new/results/retro/clm/daily/asc.tmp2 ../data/conus.new/results/retro/clm/monthly/asc ro
wrap_prep_ro_for_kingtse.pl noah_2.8.new ../data/conus.new/results/retro/noah_2.8.new/daily/asc wb ../data/conus.new/results/retro/noah_2.8.new/daily/asc.tmp ../data/conus.new/results/retro/noah_2.8.new/daily/asc.tmp2 ../data/conus.new/results/retro/noah_2.8.new/monthly/asc ro
#wrap_prep_ro_for_kingtse.pl sac.new ../data/conus.new/results/retro/sac.new/daily/asc wb ../data/conus.new/results/retro/sac.new/daily/asc.tmp ../data/conus.new/results/retro/sac.new/daily/asc.tmp2 ../data/conus.new/results/retro/sac.new/monthly/asc ro
